In [107]:
import math as m
import decimal
import scipy.stats as stats
import random
import numpy as np
from scipy.stats import chi2

In [92]:
#1.1
def pi_bbp(precision):
    decimal.getcontext().prec = precision + 1
    pi = decimal.Decimal(0)
    for k in range(precision):
        pi += (decimal.Decimal(1)/(16**k))*((decimal.Decimal(4)/(8*k+1))-(decimal.Decimal(2)/(8*k+4))-(decimal.Decimal(1)/(8*k+5))-(decimal.Decimal(1)/(8*k+6)))
    return pi

prak_pi = pi_bbp(1000) - 3
pi_str = str(prak_pi)[2:]
pi_dig = [int(d) for d in pi_str]
a = np.full(10,0)
for i in range(len(pi_dig)):
  a[pi_dig[i]]+=1
print(a)
b = np.full(10,0)
c = np.random.sample(1000)
c = [int(d*10) for d in c]
print(c)
for i in range(len(c)):
  b[c[i]]+=1
stats.chisquare(f_obs=a , f_exp=b)

[ 93 116 103 102  93  97  94  95 101 106]
[4, 2, 4, 5, 9, 8, 8, 6, 4, 4, 9, 9, 1, 7, 8, 2, 9, 5, 8, 1, 4, 8, 9, 6, 4, 2, 1, 7, 4, 2, 0, 3, 9, 5, 4, 0, 1, 3, 1, 0, 2, 5, 8, 5, 1, 7, 5, 5, 1, 0, 8, 2, 2, 7, 9, 8, 4, 3, 6, 5, 5, 0, 1, 7, 1, 2, 5, 9, 6, 2, 2, 7, 4, 6, 8, 3, 7, 6, 7, 2, 6, 1, 3, 3, 5, 3, 5, 5, 1, 7, 1, 3, 6, 7, 2, 5, 1, 6, 2, 5, 9, 4, 1, 5, 6, 5, 8, 8, 0, 7, 9, 1, 8, 1, 2, 8, 2, 5, 3, 9, 7, 0, 8, 8, 2, 3, 8, 0, 4, 7, 9, 2, 4, 3, 7, 9, 1, 4, 3, 2, 3, 6, 2, 7, 7, 9, 8, 2, 6, 7, 9, 8, 9, 4, 3, 7, 1, 7, 6, 6, 9, 0, 5, 2, 8, 3, 4, 8, 2, 7, 7, 1, 2, 6, 3, 5, 1, 5, 0, 1, 0, 2, 0, 3, 7, 2, 1, 0, 0, 0, 2, 7, 0, 5, 8, 6, 8, 7, 8, 2, 0, 4, 7, 1, 4, 2, 2, 5, 1, 7, 6, 7, 8, 7, 6, 4, 8, 1, 1, 5, 5, 9, 8, 3, 6, 3, 0, 0, 2, 5, 4, 9, 8, 0, 0, 3, 7, 6, 0, 6, 6, 0, 0, 4, 0, 2, 8, 4, 5, 4, 6, 2, 8, 2, 9, 1, 6, 8, 3, 1, 8, 8, 2, 9, 3, 7, 8, 1, 7, 5, 8, 6, 0, 1, 6, 1, 5, 5, 2, 6, 1, 2, 8, 8, 3, 5, 8, 1, 8, 0, 2, 3, 8, 5, 7, 5, 8, 6, 6, 6, 2, 6, 8, 1, 0, 4, 2, 3, 6, 8, 8, 9, 5, 2, 4, 8, 4, 0, 2, 

Power_divergenceResult(statistic=11.540736951938962, pvalue=0.2404552316119401)

In [115]:
#1.2
N = 2020
Nm = 527
Nd = 476
Nmd = N - Nm - Nd
t = (Nmd+ 2*Nm)/(2*N)
p = 0.05
print(t)
RealStat = [Nd/N, Nmd/N , Nm/N]
OStat = [(1-t)**2, (1-t)*t , t**2]
print(OStat)
print(RealStat)
RS = np.array([Nd, Nmd,Nd])
OS = np.array([int(N*(1-t)**2),int(2*N*(1-t)*t),int(N*t**2) ])
print(RS)
print(OS)
chi2_stat = ((OS - RS)/ RS).sum()
chi2_crit = chi2.ppf(1- 0.05, 2)
p_v = 1 - chi2.cdf(chi2_stat, 2)

print(p_v)


0.5126237623762376
[0.23753559700029409, 0.24984064062346828, 0.26278312175276936]
[0.23564356435643563, 0.5034653465346535, 0.2608910891089109]
[ 476 1017  476]
[ 479 1009  530]
0.9455951012628329


In [162]:
#1.3
import pandas as pd
import scipy.stats as stats
f = pd.read_csv("Priem.txt", delimiter=';')

In [156]:
m = f[(f["Пол"] == "МУЖСКОЙ")]
BM = list(m["ЕГЭ...матем."])
BR = list(m["ЕГЭ...рус.яз."])
SM = list(m["Сумма.баллов"])
d = f[(f["Пол"] == "ЖЕНСКИЙ")]
BMD = list(d["ЕГЭ...матем."])
BRD = list(d["ЕГЭ...рус.яз."])
SD = list(d["Сумма.баллов"])

In [177]:

t1,p1 = stats.ttest_ind(SM,SD)
print(t,p)


-0.7336120849929042 0.46330908415330374
